import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';

const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
  style: 'normal',
  variable: '--font-rubik',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex justify-center items-center w-screen min-h-screen bg-very-dark-blue ${rubik.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
